config/routes.rb
Rails.application.routes.draw do

  resources :interactions do
    member do
      post '' => 'interactions#reply'
    end
  end

  resources :posts do
    collection do
      get 'newest'
      get 'ask'
    end
    member do
      delete '' => 'contributions#destroy'
      post '' => 'posts#comment'
    end
  end
  resources :users do
    member do
      get 'user_submissions'
      get 'user_comments'
      get 'upvoted_submissions'
      get 'upvoted_comments'
    end
  end
  get '/login' => 'users#create'
  get '/logout' => 'users#logout'


  resources :contributions do
    member do
      put 'like'
      delete 'unlike'
    end
  end

  resources :comments

  namespace :api, defaults: {format: 'json'} do
    post '/login' => '/api/users#create'
    resources :posts do
      member do
        post 'like' => '/api/contributions#like'
        delete 'like' => '/api/contributions#unlike'
        get 'comments' => '/api/comments#index'
      end
      collection do
        get 'newest'
        get 'ask'
      end
    end
    resources :users do
      member do
        get 'submissions'
        get 'comments'
        get 'upvoted_submissions'
        get 'upvoted_comments'
      end
    end
    resources :comments do
      member do
        get 'replies'
        post 'like' => '/api/contributions#like'
        delete 'like' => '/api/contributions#unlike'
      end
    end
    resources :replies do
      member do
        post 'like' => '/api/contributions#like'
        delete 'like' => '/api/contributions#unlike'
        get 'replies'
      end
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'posts#index'
end

app/models/comment.rb
class Comment < Interaction
  belongs_to :post

  validates :text, presence: true

end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :destroy, :replies]
  before_action :api_auth
  skip_forgery_protection

  def index
    Contribution.current_user = current_api_user
    @json = []
    @post = Post.find(params[:id])
    render json: @post.comments.as_json(except: [:contribution_id, :updated_at, :title, :url, :tipo], :methods => [:type, :author, :respostes, :liked]), status: :ok
  end

  def show
    Contribution.current_user = current_api_user
    render json: @comment.as_json(except: [:contribution_id, :updated_at, :title, :url, :tipo], :methods => [:author, :liked]), status: :ok
  end

  def create
    Contribution.current_user = current_api_user
    @post = Post.find(params[:comment][:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user = current_api_user
    if @comment.save
      render json: @comment.as_json(except: [:contribution_id, :updated_at, :title, :url, :tipo], :methods => [:author, :liked]), status: :created
    else
      render json: @comment.errors, status: :bad_request
    end
  end

  def replies
    Contribution.current_user = current_api_user
    @replies = @comment.replies
    render json: @replies.as_json(except: [:updated_at, :title, :url, :tipo], :methods => [:type, :author, :respostes, :liked]), status: :ok
  end

  def destroy
    if @comment.user_id == current_api_user.id
      @comment.likes.destroy_all
      @comment.destroy
      head :no_content
    else
      head :forbidden
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_comment, only: [:show]

  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/show.html.erb
<html lang="en"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><center><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
      <a href="/posts/newest">new</a> | <a href="/posts/ask">ask</a> | <% if cookies.signed[:user_id] %><%= link_to 'threads', user_comments_user_path(cookies.signed[:user_id]) %><% else %><%= link_to 'threads', new_post_path %><% end %> | <a href="/posts/new">submit</a>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]= comment_path(@comment) %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %></td>
  </tr></table></td></tr>
  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
      <tr>
        <td width="5px"><% if @comment.likes.find_by(user_id: cookies.signed[:user_id]) %>
            <div class="hiddenarrow"></div>
          <% elsif @comment.user_id == cookies.signed[:user_id] %>
            <div style="color:#ff6600">*</div>
          <% else %>
            <%= link_to like_contribution_path(@comment), method: :put do %>
              <div class="votearrow" title="upvote"></div>
            <% end %>
          <% end %></td>
        <td class="subtext" colspan="3">
          <% if @comment.user_id == cookies.signed[:user_id] %>
            <%= link_to @comment.user.name, edit_user_path(@comment.user) %>
          <%else %>
            <%= link_to @comment.user.name, user_path(@comment.user) %>
          <% end %>
          <%= link_to time_ago_in_words(@comment.created_at)+" ago", comment_path(@comment) %>
          <% if @comment.likes.find_by(user_id: cookies.signed[:user_id]) %>
            | <%= link_to "Unvote", unlike_contribution_path(@comment), method: :delete %>
          <% end %>
        </td></tr>
      <tr>
        <td style="position:relative;left:20px;color:#000000" class="text" colspan="3"><%= simple_format(@comment.text) %></td>
      </tr>
    <tr>

    </tr>
    </tbody>
  </table>


  </tr></tbody></table></body></center></html>