config/routes.rb
Rails.application.routes.draw do

  resources :interactions do
    member do
      post '' => 'interactions#reply'
    end
  end

  resources :posts do
    collection do
      get 'newest'
      get 'ask'
    end
    member do
      delete '' => 'contributions#destroy'
      post '' => 'posts#comment'
    end
  end
  resources :users do
    member do
      get 'user_submissions'
      get 'user_comments'
      get 'upvoted_submissions'
      get 'upvoted_comments'
    end
  end
  get '/login' => 'users#create'
  get '/logout' => 'users#logout'


  resources :contributions do
    member do
      put 'like'
      delete 'unlike'
    end
  end

  resources :comments

  namespace :api, defaults: {format: 'json'} do
    post '/login' => '/api/users#create'
    resources :posts do
      member do
        post 'like' => '/api/contributions#like'
        delete 'like' => '/api/contributions#unlike'
        get 'comments' => '/api/comments#index'
      end
      collection do
        get 'newest'
        get 'ask'
      end
    end
    resources :users do
      member do
        get 'submissions'
        get 'comments'
        get 'upvoted_submissions'
        get 'upvoted_comments'
      end
    end
    resources :comments do
      member do
        get 'replies'
        post 'like' => '/api/contributions#like'
        delete 'like' => '/api/contributions#unlike'
      end
    end
    resources :replies do
      member do
        post 'like' => '/api/contributions#like'
        delete 'like' => '/api/contributions#unlike'
        get 'replies'
      end
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'posts#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contributions, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  validates :name, presence: true
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_action :set_user, only: [:show, :update]
  before_action :api_auth, except: :create
  skip_forgery_protection

  # GET /users/1
  # GET /users/1.json
  def show
    if current_api_user.id == @user.id
      render json: @user.as_json(except: [:updated_at])
    else
      render json: @user.as_json(except: [:google_id, :updated_at])
    end
  end

  # GET /users/1/submissions
  def submissions
    Contribution.current_user = current_api_user
    @id = params[:id]
    @posts = Post.all.where("user_id= ?", @id).order('points DESC')
    render json: @posts.as_json(except: [:post_id, :contribution_id, :updated_at], :methods => [:author, :liked])
  end

  # GET /users/1/comments
  def comments
    Contribution.current_user = current_api_user
    @id = params[:id]
    @comments = Comment.all.where("user_id = ?", @id) + Reply.all.where("user_id = ?", @id)
    @comments = @comments.sort_by { |e| -e[:points] }
    render json: @comments.as_json(only: [:type, :id, :text, :user_id, :points, :created_at, :post_id, :contribution_id], :methods => [:author, :liked]), status: :ok
  end

  # GET /users/1/upvoted_submissions
  def upvoted_submissions
    Contribution.current_user = current_api_user
    @user = User.find(params[:id])
    if current_api_user.id == @user.id
      @contributions = []
      @likes = current_api_user.likes
      @likes.each do |like|
        if like.contribution.type == "Post"
          @contributions << like.contribution if like.contribution
        end
      end
      @contributions = @contributions.sort_by { |e| -e[:points] }
      render json: @contributions.as_json(except: [:post_id, :contribution_id, :updated_at], :methods => :author), status: :ok
    else
      head :forbidden
    end
  end

  # GET /users/1/upvoted_comments
  def upvoted_comments
    Contribution.current_user = current_api_user
    @user = User.find(params[:id])
    if current_api_user.id == @user.id
      @contributions = []
      @likes = current_api_user.likes
      @likes.each do |like|
        if like.contribution.type == "Comment" || like.contribution.type == "Reply"
          @contributions << like.contribution if like.contribution
        end
      end
      @contributions = @contributions.sort_by { |e| -e[:points] }
      render json: @contributions.as_json(only: [:type, :id, :text, :user_id, :points, :created_at, :post_id, :contribution_id], :methods => :author), status: :ok
    else
      head :forbidden
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.id == current_api_user.id
      if @user.update(user_params)
        render json: @user.as_json(except: [:updated_at]), status: :ok
      else
        render json: @user.errors, status: :bad_request
      end
    else
      render json: '', status: :forbidden
    end
  end

  def create
    if user = User.find_by_google_id(params[:google_id])
      render json: user.as_json(only: [:id]), status: :ok
    else
      @user = User.new
      @user.name = params[:name]
      @user.google_id = params[:google_id]
      @user.save
      render json: @user.as_json(only: [:id]), status: :created
    end
  end


  private


  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :about)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/user_submissions
  def user_submissions
    @id = params[:id]
    @posts = Post.all.where("user_id= ?", @id)
  end

  # GET /users/1/user_comments
  def user_comments
    @id = params[:id]
    @comments = Comment.all.where("user_id = ?", @id) + Reply.all.where("user_id = ?", @id)
  end

  # GET /users/1/upvoted_submissions
  def upvoted_submissions
    @likes = current_user.likes.all

  end

  # GET /users/1/upvoted_comments
  def upvoted_comments
    @likes = current_user.likes.all
  end

  # GET /users/1/edit
  def edit
  end

  def logout
    cookies.delete(:user_id)
    callback = cookies.signed[:callback]
    cookies.delete(:callback)
    redirect_to root_path
  end

  # POST /users
  # POST /users.json
  def create
    id_token = flash[:google_sign_in_token]
    if user = authenticate_with_google(id_token)
      cookies.signed[:user_id] = user.id
    else
      @user = User.new
      @user.name = GoogleSignIn::Identity.new(id_token).name
      @user.google_id = GoogleSignIn::Identity.new(id_token).user_id
      @user.save
      cookies.signed[:user_id] = @user.id
    end
    callback = cookies.signed[:callback]
    cookies.delete(:callback)
    redirect_to callback
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to edit_user_path(@user)}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.likes.each do |like|
      @contribution = like.contribution
      @contribution.points -= 1
      @contribution.save
    end
    @user.likes.destroy_all
    @user.contributions.destroy_all
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url}
      format.json { head :no_content }
    end
  end

  private

    def authenticate_with_google(id_token)
      if id_token
        User.find_by_google_id(GoogleSignIn::Identity.new(id_token).user_id)
      elsif error = flash[:google_sign_in_error]
        logger.error "Google authentication error: #{error}"
        nil
      end
    end


    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :about)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <html lang="en"><center><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
    <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
    <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
    <title>Hacker News</title></head><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%  ">
    <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%"  style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
      <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
              <a href="/posts/newest">new</a> | <a href="/posts/ask">ask</a> | <% if cookies.signed[:user_id] %><%= link_to 'threads', user_comments_user_path(cookies.signed[:user_id]) %><% else %><%= link_to 'threads', new_post_path %><% end %> | <a href="/posts/new">submit</a></span></td>
      <td style="text-align:right;color:#000000">
        <% cookies.signed[:callback]='/posts/ask' %>
        <% if cookies.signed[:user_id] %>
          <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
        <% else %>
          <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
        <%end %>
      </td>
    </tr></table></td></tr>
    <tbody>
    <tr><table style="background-color:#f6f6ef;width:85%">
      <tbody>
      <tr><table style="background-color:#f6f6ef;width:85%">
        <tbody>
        <tr>
          <td width="60px" class="text">user:</td>
          <td width="auto" ><%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style:"color:#3c963c" %></td>
        </tr>
        <tr>
          <td width="auto" class="text">created:</td>
          <td width="auto" ><%= link_to time_ago_in_words(User.find(cookies.signed[:user_id]).created_at)+" ago", edit_user_path(User.find(cookies.signed[:user_id]))%></td>
        </tr>
        <tr>
          <td width="auto" class="text">karma:</td>
          <td width="auto" ><%= User.find(cookies.signed[:user_id]).karma %></td>
        </tr>
        <tr>
          <td width="auto" class="text">api-key:</td>
          <td width="auto" ><%= User.find(cookies.signed[:user_id]).google_id %></td>
        </tr>
        <tr>
          <td valign="top" width="auto" class="text">about:</td>
          <td class="field" width="auto"><%= form.text_area :about, rows:5, cols:60 %></td>
        </tr>
        <tr>
          <td></td>
          <td><%= link_to "submissions", user_submissions_user_path(@user), style:"color: #000000;font-size:10pt;text-decoration: underline;" %></td>
        </tr>
        <tr>
          <td></td>
          <td><%= link_to "comments", user_comments_user_path(@user), style:"color: #000000;font-size:10pt;text-decoration: underline;" %></td>
        </tr>
        <tr>
          <td></td>
          <td style="color:#000000"><%= link_to "upvoted submissions", upvoted_submissions_user_path(@user), style:"color: #000000;font-size:10pt;text-decoration: underline;" %> / <%= link_to "comments", upvoted_comments_user_path(@user), style:"color: #000000;font-size:10pt;text-decoration: underline;" %></td>
        </tr>
        <tr>
          <td>
            <div class="actions">
              <%= form.button 'update', type:'submit' %>
            </div>
          </td>
        </tr>
        </tbody>
      </table></tr>
      </tbody>
    </table>
    </tr></tbody></table></body></center></html>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.karma %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/upvoted_comments.html.erb
<html lang="en"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><center><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
      <a href="/posts/newest">new</a> | <a href="/posts/ask">ask</a> | <% if cookies.signed[:user_id] %><%= link_to 'threads', user_comments_user_path(cookies.signed[:user_id]) %><% else %><%= link_to 'threads', new_post_path %><% end %> | <a href="/posts/new">submit</a> | <a style="color:#ffffff">upvoted comments</a></span></td>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]= upvoted_comments_user_path(cookies.signed[:user_id]) %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %></td>
  </tr></table></td></tr>
  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
    <% @likes.each do |like| %>
      <% if like.contribution.type == "Comment" || like.contribution.type == 'Reply' %>
      <tr>
        <td class="subtext" colspan="3" style="position:relative;left:10px;">
          <% if like.contribution.user_id == cookies.signed[:user_id] %>
            <%= link_to like.contribution.user.name, edit_user_path(like.contribution.user) %>
          <%else %>
            <%= link_to like.contribution.user.name, user_path(like.contribution.user) %>
          <% end %>
          <%= link_to time_ago_in_words(like.contribution.created_at)+" ago", interaction_path(like.contribution) %>
          <% if like.contribution.likes.find_by(user_id: cookies.signed[:user_id]) %>
            | <%= link_to "Unvote", unlike_contribution_path(like.contribution), method: :delete %>
          <% end %>
          | <% if like.contribution.type == "Reply" %>
            <%= link_to "parent", interaction_path(like.contribution.contribution_id) %>
          <% elsif like.contribution.type == "Comment" %>
            <%= link_to "parent", post_path(like.contribution.post_id) %>
          <% end %>
          | on: <%= link_to Post.find(like.contribution.post_id).title, post_path(like.contribution.post_id) %>
        </td></tr>
      <tr>
        <td style="position:relative;left:10px;color:#000000" class="text" colspan="3"><%= simple_format(like.contribution.text) %></td>
      </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>


  </tr></tbody></table></body></center></html>

app/views/users/upvoted_submissions.html.erb
<html lang="en"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><center><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
      <a href="/posts/newest">new</a> | <a href="/posts/ask">ask</a> | <% if cookies.signed[:user_id] %><%= link_to 'threads', user_comments_user_path(cookies.signed[:user_id]) %><% else %><%= link_to 'threads', new_post_path %><% end %> | <a href="/posts/new">submit</a> | <a style="color:#ffffff">upvoted submissions</a></span></td>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]= upvoted_submissions_user_path(cookies.signed[:user_id]) %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %></td>
  </tr></table></td></tr>
  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
    <% num=1 %>
    <% @likes.each do |like| %>
      <% if like.contribution.type == "Post" %>
      <tr>
        <td width="10px"><%= num %>.</td>
        <td><%= link_to like.contribution.title, post_path(like.contribution), style:"color:#000000" %></td>
      </tr>
      <tr>
        <td></td>
        <td style="" class="subtext" colspan="3"><%= like.contribution.points %> points by
        <% if like.contribution.user_id == cookies.signed[:user_id] %>
          <%= link_to like.contribution.user.name, edit_user_path(like.contribution.user) %>
        <%else %>
          <%= link_to like.contribution.user.name, user_path(like.contribution.user) %>
        <% end %>
        <%= link_to time_ago_in_words(like.contribution.created_at)+" ago", post_path(like.contribution) %>
        <% if like.contribution.likes.find_by(user_id: cookies.signed[:user_id]) %>
          | <%= link_to "Unvote", unlike_contribution_path(like.contribution), method: :delete %>
        <% end %>
        <% if cookies.signed[:user_id] == like.contribution.user.id %>
          | <%= link_to "Edit", edit_post_path(like.contribution) %> | <%= link_to "Delete", like.contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %>
        <% num+=1 %>
      <% end %>
    <% end %>
    </tbody>
  </table>


  </tr></tbody></table></body></center></html>

app/views/users/user_comments.html.erb
<html lang="en"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><center><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
      <a href="/posts/newest">new</a> | <a href="/posts/ask">ask</a> | <% if cookies.signed[:user_id] %><%= link_to 'threads', user_comments_user_path(cookies.signed[:user_id]) %><% else %><%= link_to 'threads', new_post_path %><% end %> | <a href="/posts/new">submit</a> | <a style="color:#ffffff"><%= User.find(@id).name+"'s comments" %></a></span></td>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]= user_comments_user_path %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %></td>
  </tr></table></td></tr>
  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
    <% num=1 %>
    <% @comments.each do |comment| %>
      <tr>
        <td width="5px"><% if comment.likes.find_by(user_id: cookies.signed[:user_id]) %>
            <div class="hiddenarrow"></div>
          <% elsif comment.user_id == cookies.signed[:user_id] %>
            <div style="color:#ff6600">*</div>
          <% else %>
            <%= link_to like_contribution_path(comment), method: :put do %>
              <div class="votearrow" title="upvote"></div>
            <% end %>
          <% end %></td>
        <td class="subtext" colspan="3">
          <% if comment.user_id == cookies.signed[:user_id] %>
            <%= link_to comment.user.name, edit_user_path(comment.user) %>
          <%else %>
            <%= link_to comment.user.name, user_path(comment.user) %>
          <% end %>
          <%= link_to time_ago_in_words(comment.created_at)+" ago", interaction_path(comment) %>
          <% if comment.likes.find_by(user_id: cookies.signed[:user_id]) %>
            | <%= link_to "Unvote", unlike_contribution_path(comment), method: :delete %>
          <% end %>
          | <% if comment.type == "Reply" %>
            <%= link_to "parent", interaction_path(comment.contribution_id) %>
          <% elsif comment.type == "Comment" %>
            <%= link_to "parent", post_path(comment.post_id) %>
          <% end %>
          | on: <%= link_to Post.find(comment.post_id).title, post_path(comment.post_id) %>
        </td></tr>
      <tr>
        <td style="position:relative;left:20px;color:#000000" class="text" colspan="3"><%= simple_format(comment.text) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>


  </tr></tbody></table></body></center></html>

app/views/users/user_submissions.html.erb
<html lang="en"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><center><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
      <a href="/posts/newest">new</a> | <a href="/posts/ask">ask</a> | <% if cookies.signed[:user_id] %><%= link_to 'threads', user_comments_user_path(cookies.signed[:user_id]) %><% else %><%= link_to 'threads', new_post_path %><% end %> | <a href="/posts/new">submit</a> | <a style="color:#ffffff"><%= User.find(@id).name+"'s submissions" %></a></span></td>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]= user_submissions_user_path %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %></td>
  </tr></table></td></tr>
  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
    <% num=1 %>
    <% @posts.each do |post| %>
      <tr>
        <td width="10px"><%= num %>.</td>
        <td width="5px"><% if post.likes.find_by(user_id: cookies.signed[:user_id]) %>
            <div class="hiddenarrow"></div>
          <% elsif post.user_id == cookies.signed[:user_id] %>
            <div style="color:#ff6600">*</div>
          <% else %>
            <%= link_to like_contribution_path(post), method: :put do %>
              <div class="votearrow" title="upvote"></div>
            <% end %>
          <% end %></td>
        <td><%= link_to post.title, post_path(post) %></td>
      </tr>
      <tr><td style="position:relative;left:53px" class="subtext" colspan="3"><%= post.points %> points by
        <% if post.user_id == cookies.signed[:user_id] %>
          <%= link_to post.user.name, edit_user_path(post.user) %>
        <%else %>
          <%= link_to post.user.name, user_path(post.user) %>
        <% end %>
        <%= link_to time_ago_in_words(post.created_at)+" ago", post_path(post) %>
        <% if post.likes.find_by(user_id: cookies.signed[:user_id]) %>
          | <%= link_to "Unvote", unlike_contribution_path(post), method: :delete %>
        <% end %>
        <% if cookies.signed[:user_id] == post.user.id %>
          | <%= link_to "Edit", edit_post_path(post) %> | <%= link_to "Delete", post, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %>
        <% num+=1 %>
    <% end %>
    </tbody>
  </table>


  </tr></tbody></table></body></center></html>