config/routes.rb
Rails.application.routes.draw do

  resources :interactions do
    member do
      post '' => 'interactions#reply'
    end
  end

  resources :posts do
    collection do
      get 'newest'
      get 'ask'
    end
    member do
      delete '' => 'contributions#destroy'
      post '' => 'posts#comment'
    end
  end
  resources :users do
    member do
      get 'user_submissions'
      get 'user_comments'
      get 'upvoted_submissions'
      get 'upvoted_comments'
    end
  end
  get '/login' => 'users#create'
  get '/logout' => 'users#logout'


  resources :contributions do
    member do
      put 'like'
      delete 'unlike'
    end
  end

  resources :comments

  namespace :api, defaults: {format: 'json'} do
    post '/login' => '/api/users#create'
    resources :posts do
      member do
        post 'like' => '/api/contributions#like'
        delete 'like' => '/api/contributions#unlike'
        get 'comments' => '/api/comments#index'
      end
      collection do
        get 'newest'
        get 'ask'
      end
    end
    resources :users do
      member do
        get 'submissions'
        get 'comments'
        get 'upvoted_submissions'
        get 'upvoted_comments'
      end
    end
    resources :comments do
      member do
        get 'replies'
        post 'like' => '/api/contributions#like'
        delete 'like' => '/api/contributions#unlike'
      end
    end
    resources :replies do
      member do
        post 'like' => '/api/contributions#like'
        delete 'like' => '/api/contributions#unlike'
        get 'replies'
      end
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'posts#index'
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  has_many :replies, :dependent => :destroy
  belongs_to :user
  has_many :likes, :dependent => :destroy
  cattr_accessor :current_user

  def author
    user.name
  end

  def liked
    !likes.find_by(user_id: current_user.id).nil?
  end

end

app/controllers/api/contributions_controller.rb
class Api::ContributionsController < ApplicationController
  before_action :set_contribution, only: [:like, :unlike]
  skip_forgery_protection


  def like
    if (current_api_user.id != @contribution.user_id) && !(@contribution.likes.find_by(user: current_api_user))
      @contribution.likes.create(user: current_api_user)
      @contribution.points += 1
      @contribution.save 
      head :created
    else 
      head :bad_request
    end
  end

  def unlike
    if @contribution.likes.find_by(user: current_api_user)
      @contribution.likes.find_by(user: current_api_user).destroy
      @contribution.points -= 1
      @contribution.save
      head :no_content
    else
      head :bad_request
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_contribution
    @contribution = Contribution.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contribution_params
    params.require(:contribution).permit(:title, :text, :url)
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy, :like, :unlike]

  before_action :require_login, only: [:new, :edit, :like, :create, :destroy, :like, :unlike]

  # GET /contributions/1
  # GET /contributions/1.json
  def show
  end


  def like
    @contribution.likes.create(user: current_user)
    @contribution.points += 1
    @contribution.save
    callback = cookies.signed[:callback]
    cookies.delete(:callback)
    redirect_to callback
  end

  def unlike
    @contribution.likes.find_by(user: current_user).destroy
    @contribution.points -= 1
    @contribution.save
    callback = cookies.signed[:callback]
    cookies.delete(:callback)
    redirect_to callback
  end

  # DELETE /contributions/1
  # DELETE /contributions/1.json
  def destroy
    @contribution.likes.destroy_all

    @contribution.destroy

    respond_to do |format|
      format.html { redirect_to newest_posts_path}
      format.json { head :no_content }
    end
  end

  private
  def require_login
    unless current_user
      repost('/google_sign_in/authorization',
             params: { proceed_to: '/login' },
             options: { authenticity_token: :auto })

    end
  end
    # Use callbacks to share common setup or constraints between actions.
  def set_contribution
    @contribution = Contribution.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def contribution_params
    params.require(:contribution).permit(:title, :text, :url)
  end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_form.html.erb
<%= form_with(model: contribution, local: true) do |form| %>
    <% if @contribution.errors.any? %>

      <div style="margin-left: 7.5%" id="error_explanation">
        <h2><%= pluralize(@contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

        <ul>
          <% @contribution.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


  <center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
    <tr><td bgcolor="#ff6600">
      <table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
        <tr><td style="width:18px;padding-right:4px">
          <a href="/">
            <img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px #ffffff solid;"></a></td>
          <td style="line-height:12pt; height:10px;"><span class="pagetop"><b style="color: #000000">Submit</b></span></td></tr></table></td></tr>
    <tr style="height:10px"></tr>
    <tr><td>
      <table border="0">
        <tr><td>title</td>
        <td class="field">
        <%= form.text_field :title, size:50 %>
          </td></tr>
        <tr><td>url</td>
          <td class="field">
            <%= form.text_field :url, size:50  %>
            </td></tr>
        <tr><td></td><td><b>or</b></td></tr>
        <tr><td>text</td>
          <td class="field">
            <%= form.text_area :text, rows:4, cols:51 %>
            </td></tr>
        <tr><td></td>
        <td class="actions">
          <%= form.submit "submit" %>
        </td></tr>
        <tr style="height:20px"></tr><tr><td></td><td>Leave url blank to submit a question for discussion. If there
        is no url, the text (if any) will appear at the top of the
        thread.</td></tr>
      </table>
    </td></tr>
  </table></center>
<% end %>

app/views/contributions/ask.html.erb
<html lang="en"><center><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%  ">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%"  style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
              <a href="/contributions/newest">new</a> | <a style="color:#ffffff" href="/contributions/ask">ask</a> | <a href="/contributions/threads">threads</a> | <a href="/contributions/new">submit</a></span></td>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]='/contributions/ask' %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %>
    </td>
  </tr></table></td></tr>
  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
    <% num=1 %>
    <% @contributions.each do |contribution| %>
      <tr>
        <td width="10px"><%= num %>.</td>
        <td width="5px"><% if contribution.likes.find_by(user_id: cookies.signed[:user_id]) %>
            <div class="hiddenarrow"></div>
          <% elsif contribution.user_id == cookies.signed[:user_id] %>
            <div style="color:#ff6600">*</div>
          <% else %>
            <%= link_to like_contribution_path(contribution), method: :put do %>
              <div class="votearrow" title="upvote"></div>
            <% end %>
          <% end %></td>
        <td><%= link_to contribution.title, contribution_path(contribution) %></td>
      </tr>
      <tr><td style="position:relative;left:53px" class="subtext" colspan="3"><%= contribution.points %> points by <%= link_to contribution.user.name, user_path(contribution.user) %> <%= link_to time_ago_in_words(contribution.created_at)+" ago", contribution_path(contribution) %>
        <% if contribution.likes.find_by(user_id: cookies.signed[:user_id]) %>
          | <%= link_to "Unvote", unlike_contribution_path(contribution), method: :delete %>
        <% end %>
        <% if cookies.signed[:user_id] == contribution.user.id %>
          | <%= link_to "Edit", edit_contribution_path(contribution) %> | <%= link_to "Delete", contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %></td></tr>

      <% num+=1 %>
    <% end %>
    </tbody>
  </table>


  </tr></tbody></table></body></center></html>

app/views/contributions/index.html.erb
<html lang="en"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><center><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
      <a href="/contributions/newest">new</a> | <a href="/contributions/ask">ask</a> | <a href="/contributions/threads">threads</a> | <a href="/contributions/new">submit</a></span></td>
      <td style="text-align:right;color:#000000">
        <% cookies.signed[:callback]='/' %>
        <% if cookies.signed[:user_id] %>
            <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
          <% else %>
          <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
        <%end %></td>
  </tr></table></td></tr>
<tbody>
<tr><table style="background-color:#f6f6ef;width:85%">
  <tbody>
  <% num=1 %>
    <% @contributions.each do |contribution| %>
    <tr>
      <td width="10px"><%= num %>.</td>
      <td width="5px"><% if contribution.likes.find_by(user_id: cookies.signed[:user_id]) %>
            <div class="hiddenarrow"></div>
          <% elsif contribution.user_id == cookies.signed[:user_id] %>
          <div style="color:#ff6600">*</div>
          <% else %>
          <%= link_to like_contribution_path(contribution), method: :put do %>
            <div class="votearrow" title="upvote"></div>
          <% end %>
        <% end %></td>
      <td><%= link_to contribution.title, contribution.url %></td>
    </tr>
    <tr><td style="position:relative;left:53px" class="subtext" colspan="3"><%= contribution.points %> points by <%= link_to contribution.user.name, user_path(contribution.user) %> <%= link_to time_ago_in_words(contribution.created_at)+" ago", contribution_path(contribution) %>
      <% if contribution.likes.find_by(user_id: cookies.signed[:user_id]) %>
        | <%= link_to "Unvote", unlike_contribution_path(contribution), method: :delete %>
      <% end %>
      <% if cookies.signed[:user_id] == contribution.user.id %>
        | <%= link_to "Edit", edit_contribution_path(contribution) %> | <%= link_to "Delete", contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
      <% end %>
    <% num+=1 %>
  <% end %>
  </tbody>
</table>


</tr></tbody></table></body></center></html>

app/views/contributions/newest.html.erb
<html lang="en"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><center><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
              <a style="color:#ffffff" href="/contributions/newest">new</a> | <a href="/contributions/ask">ask</a> | <a href="/contributions/threads">threads</a> | <a href="/contributions/new">submit</a></span></td>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]='/contributions/newest' %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %>
    </td>
  </tr></table></td></tr>
  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
    <% num=1 %>
    <% @contributions.each do |contribution| %>
      <tr>
        <td width="10px"><%= num %>.</td>
        <td width="5px"><% if contribution.likes.find_by(user_id: cookies.signed[:user_id]) %>
            <div class="hiddenarrow"></div>
          <% elsif contribution.user_id == cookies.signed[:user_id] %>
            <div style="color:#ff6600">*</div>
          <% else %>
            <%= link_to like_contribution_path(contribution), method: :put do %>
              <div class="votearrow" title="upvote"></div>
            <% end %>
          <% end %></td>
        <% if contribution.url != "" %>
          <td><%= link_to contribution.title, contribution.url %></td>
        <% else %>
          <td><%= link_to contribution.title, contribution_path(contribution) %></td>
        <% end %>
      </tr>
      <tr><td style="position:relative;left:53px" class="subtext" colspan="3"><%= contribution.points %> points by <%= link_to contribution.user.name, user_path(contribution.user) %> <%= link_to time_ago_in_words(contribution.created_at)+" ago", contribution_path(contribution) %>
        <% if contribution.likes.find_by(user_id: cookies.signed[:user_id]) %>
          | <%= link_to "Unvote", unlike_contribution_path(contribution), method: :delete %>
        <% end %>
        <% if cookies.signed[:user_id] == contribution.user.id %>
          | <%= link_to "Edit", edit_contribution_path(contribution) %> | <%= link_to "Delete", contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %></td></tr>

      <% num+=1 %>
    <% end %>
    </tbody>
  </table>


  </tr></tbody></table></body></center></html>

app/views/contributions/show.html.erb
<html lang="en"><center><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%  ">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%"  style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
              <a href="/contributions/newest">new</a> | <a href="/contributions/ask">ask</a> | <a href="/contributions/threads">threads</a> | <a href="/contributions/new">submit</a></span></td>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]='/contributions/ask' %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %>
    </td>

  </tr></table></td></tr>

  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
    <tr>
      <td width="5px"><% if @contribution.likes.find_by(user_id: cookies.signed[:user_id]) %>
          <div class="hiddenarrow"></div>
        <% elsif @contribution.user_id == cookies.signed[:user_id] %>
          <div style="color:#ff6600">*</div>
        <% else %>
          <%= link_to like_contribution_path(@contribution), method: :put do %>
            <div class="votearrow" title="upvote"></div>
          <% end %>
        <% end %></td>
      <td><%= link_to @contribution.title, contribution_path(@contribution) %></td>
    </tr>
    <tr><td style="position:relative;left:20px" class="subtext" colspan="3"><%= @contribution.points %> points by <%= link_to @contribution.user.name, user_path(@contribution.user) %> <%= link_to time_ago_in_words(@contribution.created_at)+" ago", contribution_path(@contribution) %>
      <% if @contribution.likes.find_by(user_id: cookies.signed[:user_id]) %>
        | <%= link_to "Unvote", unlike_contribution_path(@contribution), method: :delete %>
      <% end %>
      <% if cookies.signed[:user_id] == @contribution.user.id %>
        | <%= link_to "Edit", edit_contribution_path(@contribution) %> | <%= link_to "Delete", @contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
      <% end %></td></tr>
      <tr>
      <td style="position:relative;left:20px" class="text" colspan="3"><%= simple_format(@contribution.text) %></td>
      </tr>
      <tr>
        <td style="position:relative;left:20px" class="text" colspan="3"><%= text_area_tag( :message, "",size: "60x6" ) %></td>
      </tr>
      <tr>
        <td style="position:relative;left:20px" class="text" colspan="3"> <%= button_to 'add comment' %></td>
      </tr>
    </tbody></table>

</table></body></center></html>


<p id="notice"><%= notice %></p>

app/views/contributions/user_submissions.html.erb
<html lang="en"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><center><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
      <a href="/contributions/newest">new</a> | <a href="/contributions/ask">ask</a> | <a href="/contributions/threads">threads</a> | <a href="/contributions/new">submit</a> | <a style="color:#ffffff"><%= User.find(cookies.signed[:user_id]).name+"'s submissions" %></a></span></td>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]='/' %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %></td>
  </tr></table></td></tr>
  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
    <% num=1 %>
    <% @contributions.each do |contribution| %>
      <tr>
        <td width="10px"><%= num %>.</td>
        <td width="5px"><% if contribution.likes.find_by(user_id: cookies.signed[:user_id]) %>
            <div class="hiddenarrow"></div>
          <% elsif contribution.user_id == cookies.signed[:user_id] %>
            <div style="color:#ff6600">*</div>
          <% else %>
            <%= link_to like_contribution_path(contribution), method: :put do %>
              <div class="votearrow" title="upvote"></div>
            <% end %>
          <% end %></td>
        <td><%= link_to contribution.title, contribution.url %></td>
      </tr>
      <tr><td style="position:relative;left:53px" class="subtext" colspan="3"><%= contribution.points %> points by <%= link_to contribution.user.name, user_path(contribution.user) %> <%= link_to time_ago_in_words(contribution.created_at)+" ago", contribution_path(contribution) %>
        <% if contribution.likes.find_by(user_id: cookies.signed[:user_id]) %>
          | <%= link_to "Unvote", unlike_contribution_path(contribution), method: :delete %>
        <% end %>
        <% if cookies.signed[:user_id] == contribution.user.id %>
          | <%= link_to "Edit", edit_contribution_path(contribution) %> | <%= link_to "Delete", contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %>
        <% num+=1 %>
    <% end %>
    </tbody>
  </table>


  </tr></tbody></table></body></center></html>