config/routes.rb
Rails.application.routes.draw do

  resources :interactions do
    member do
      post '' => 'interactions#reply'
    end
  end

  resources :posts do
    collection do
      get 'newest'
      get 'ask'
    end
    member do
      delete '' => 'contributions#destroy'
      post '' => 'posts#comment'
    end
  end
  resources :users do
    member do
      get 'user_submissions'
      get 'user_comments'
      get 'upvoted_submissions'
      get 'upvoted_comments'
    end
  end
  get '/login' => 'users#create'
  get '/logout' => 'users#logout'


  resources :contributions do
    member do
      put 'like'
      delete 'unlike'
    end
  end

  resources :comments

  namespace :api, defaults: {format: 'json'} do
    post '/login' => '/api/users#create'
    resources :posts do
      member do
        post 'like' => '/api/contributions#like'
        delete 'like' => '/api/contributions#unlike'
        get 'comments' => '/api/comments#index'
      end
      collection do
        get 'newest'
        get 'ask'
      end
    end
    resources :users do
      member do
        get 'submissions'
        get 'comments'
        get 'upvoted_submissions'
        get 'upvoted_comments'
      end
    end
    resources :comments do
      member do
        get 'replies'
        post 'like' => '/api/contributions#like'
        delete 'like' => '/api/contributions#unlike'
      end
    end
    resources :replies do
      member do
        post 'like' => '/api/contributions#like'
        delete 'like' => '/api/contributions#unlike'
        get 'replies'
      end
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'posts#index'
end

app/models/post.rb
class Post < Contribution
  has_many :comments, :dependent => :destroy

  validates :title, presence: true

  validate :url_xor_text

  before_create :default_values

  def default_values
    if url.blank?
      self.tipo = "ask"
    else
      self.tipo = "url"
    end
  end

  def url_xor_text
    unless url.blank? ^ text.blank?
      errors.add(:base, 'Specify a url or a text, not both')
    end
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :set_post, only: [:show, :update, :destroy]
  before_action :api_auth
  skip_forgery_protection


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.where('tipo = ?','url').order('points DESC')
    Contribution.current_user = current_api_user
    render json: @posts.as_json(except: [:post_id, :contribution_id, :updated_at], :methods => [:author, :liked])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    Contribution.current_user = current_api_user
    render json: @post.as_json(except: [:post_id, :contribution_id, :updated_at], :methods => [:author, :liked])
  end

  def newest
    Contribution.current_user = current_api_user
    @posts = Post.all.order('created_at DESC')
    render json: @posts.as_json(except: [:post_id, :contribution_id, :updated_at], :methods => [:author, :liked])
  end

  def ask
    Contribution.current_user = current_api_user
    @posts = Post.all.where('tipo = ?','ask').order('points DESC')
    render json: @posts.as_json(except: [:post_id, :contribution_id, :updated_at], :methods => [:author, :liked])
  end

  def create
    if post_params[:url] != nil and post = Post.find_by(url: post_params[:url])
      render json: post.as_json(except: [:post_id, :contribution_id, :updated_at], :methods => :author), status: :ok
    else
      @post = Post.new(post_params)
      @user = User.find_by_google_id(request.headers['Authorization'])
      @post.user = current_api_user

      if @post.save
        @user.karma += 1
        @user.save
        render json: @post.as_json(except: [:post_id, :contribution_id, :updated_at], :methods => :author), status: :created
      else
        render json: @post.errors, status: :bad_request
      end
    end
  end

  def update
    @user = current_api_user
    if @user.id == @post.user_id
      if post_params[:url] != nil and post = Post.find_by(url: post_params[:url])
        render json: post.as_json(except: [:post_id, :contribution_id, :updated_at], :methods => :author), status: :created
      else
        if @post.update(post_params)
          render json: @post.as_json(except: [:post_id, :contribution_id, :updated_at], :methods => :author), status: :ok
        else
          render json: @post.errors, status: :bad_request
        end
      end
    else
      head :forbidden
    end
  end

  def destroy
    if current_api_user.id == @post.user_id
      @post.likes.destroy_all
      @post.destroy

      head :no_content

    else
      head :forbidden
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end


  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:url, :tipo, :title, :text)
  end

  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_action :require_login, only: [:new, :edit, :create, :destroy, :comment]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.where("tipo = ?","url").order("points DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  #GET /posts/newest
  def newest
    @posts = Post.all.order("created_at DESC")
  end

  # GET /posts/1/edit
  def edit
  end


  def ask
    @posts = Post.all.where("tipo = ?","ask").order("points DESC")
  end

  # POST /posts
  # POST /posts.json
  def create
    if post_params[:url] != "" and post = Post.find_by(url: post_params[:url])
      redirect_to post_path(post)
    else
      @post = Post.new(post_params)
      @post.user = current_user


      respond_to do |format|
        if @post.save
          @user = User.find(current_user.id)
          @user.karma += 1
          @user.save
          callback = cookies.signed[:callback]
          cookies.delete(:callback)
          format.html { redirect_to newest_posts_path}
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update

    respond_to do |format|
      if @post.update(post_params)
        callback = cookies.signed[:callback]
        cookies.delete(:callback)
        format.html { redirect_to callback}
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  #
  # SUPERCLASS



  # GET /posts/user_submissions
  def user_submissions
    @posts = Post.all.where("user_id = ?", current_user.id)
  end

  def comment
    @post = Post.find(params[:comment][:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user
    @comment.save
    callback = cookies.signed[:callback]
    cookies.delete(:callback)
    redirect_to callback
  end


  private

  def require_login
    unless current_user
      repost('/google_sign_in/authorization',
             params: { proceed_to: '/login' },
             options: { authenticity_token: :auto })

    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:url, :tipo, :title, :text)
  end

  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/ask.html.erb
<html lang="en"><center><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%  ">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%"  style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
              <a href="/posts/newest">new</a> | <a style="color:#ffffff" href="/posts/ask">ask</a> | <% if cookies.signed[:user_id] %><%= link_to 'threads', user_comments_user_path(cookies.signed[:user_id]) %><% else %><%= link_to 'threads', new_post_path %><% end %> | <a href="/posts/new">submit</a></span></td>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]='/posts/ask' %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %>
    </td>
  </tr></table></td></tr>
  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
    <% num=1 %>
    <% @posts.each do |post| %>
      <tr>
        <td width="10px"><%= num %>.</td>
        <td width="5px"><% if post.likes.find_by(user_id: cookies.signed[:user_id]) %>
            <div class="hiddenarrow"></div>
          <% elsif post.user_id == cookies.signed[:user_id] %>
            <div style="color:#ff6600">*</div>
          <% else %>
            <%= link_to like_contribution_path(post), method: :put do %>
              <div class="votearrow" title="upvote"></div>
            <% end %>
          <% end %></td>
        <td><%= link_to post.title, post_path(post) %></td>
      </tr>
      <tr><td style="position:relative;left:53px" class="subtext" colspan="3"><%= post.points %> points by
        <% if post.user_id == cookies.signed[:user_id] %>
          <%= link_to post.user.name, edit_user_path(post.user) %>
        <%else %>
          <%= link_to post.user.name, user_path(post.user) %>
        <% end %>
        <%= link_to time_ago_in_words(post.created_at)+" ago", post_path(post) %>
        <% if post.likes.find_by(user_id: cookies.signed[:user_id]) %>
          | <%= link_to "Unvote", unlike_contribution_path(post), method: :delete %>
        <% end %>
        <% if cookies.signed[:user_id] == post.user.id %>
          | <%= link_to "Edit", edit_post_path(post) %> | <%= link_to "Delete", post, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %></td></tr>

      <% num+=1 %>
    <% end %>
    </tbody>
  </table>


  </tr></tbody></table></body></center></html>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<html lang="en"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><center><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
      <a href="/posts/newest">new</a> | <a href="/posts/ask">ask</a> | <% if cookies.signed[:user_id] %><%= link_to 'threads', user_comments_user_path(cookies.signed[:user_id]) %><% else %><%= link_to 'threads', new_post_path %><% end %> | <a href="/posts/new">submit</a></span></td>
      <td style="text-align:right;color:#000000">
        <% cookies.signed[:callback]='/' %>
        <% if cookies.signed[:user_id] %>
            <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
          <% else %>
          <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
        <%end %></td>
  </tr></table></td></tr>
<tbody>
<tr><table style="background-color:#f6f6ef;width:85%">
  <tbody>
  <% num=1 %>
    <% @posts.each do |post| %>
    <tr>
      <td width="10px"><%= num %>.</td>
      <td width="5px"><% if post.likes.find_by(user_id: cookies.signed[:user_id]) %>
            <div class="hiddenarrow"></div>
          <% elsif post.user_id == cookies.signed[:user_id] %>
          <div style="color:#ff6600">*</div>
          <% else %>
          <%= link_to like_contribution_path(post), method: :put do %>
            <div class="votearrow" title="upvote"></div>
          <% end %>
        <% end %></td>
      <td><%= link_to post.title, post.url %></td>
    </tr>
    <tr><td style="position:relative;left:53px" class="subtext" colspan="3"><%= post.points %> points by
      <% if post.user_id == cookies.signed[:user_id] %>
        <%= link_to post.user.name, edit_user_path(post.user) %>
      <%else %>
        <%= link_to post.user.name, user_path(post.user) %>
      <% end %>
      <%= link_to time_ago_in_words(post.created_at)+" ago", post_path(post) %>
      <% if post.likes.find_by(user_id: cookies.signed[:user_id]) %>
        | <%= link_to "Unvote", unlike_contribution_path(post), method: :delete %>
      <% end %>
      <% if cookies.signed[:user_id] == post.user.id %>
        | <%= link_to "Edit", edit_post_path(post) %> | <%= link_to "Delete", post, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
      <% end %>
    <% num+=1 %>
  <% end %>
  </tbody>
</table>


</tr></tbody></table></body></center></html>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/newest.html.erb
<html lang="en"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><center><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
              <a style="color:#ffffff" href="/posts/newest">new</a> | <a href="/posts/ask">ask</a> | <% if cookies.signed[:user_id] %><%= link_to 'threads', user_comments_user_path(cookies.signed[:user_id]) %><% else %><%= link_to 'threads', new_post_path %><% end %> | <a href="/posts/new">submit</a></span></td>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]='/posts/newest' %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %>
    </td>
  </tr></table></td></tr>
  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
    <% num=1 %>
    <% @posts.each do |post| %>
      <tr>
        <td width="10px"><%= num %>.</td>
        <td width="5px"><% if post.likes.find_by(user_id: cookies.signed[:user_id]) %>
            <div class="hiddenarrow"></div>
          <% elsif post.user_id == cookies.signed[:user_id] %>
            <div style="color:#ff6600">*</div>
          <% else %>
            <%= link_to like_contribution_path(post), method: :put do %>
              <div class="votearrow" title="upvote"></div>
            <% end %>
          <% end %></td>
        <% if post.tipo == "url" %>
          <td><%= link_to post.title, post.url %></td>
        <% else %>
          <td><%= link_to post.title, post_path(post) %></td>
        <% end %>
      </tr>
      <tr><td style="position:relative;left:53px" class="subtext" colspan="3"><%= post.points %> points by
        <% if post.user_id == cookies.signed[:user_id] %>
          <%= link_to post.user.name, edit_user_path(post.user) %>
        <%else %>
          <%= link_to post.user.name, user_path(post.user) %>
        <% end %>
        <%= link_to time_ago_in_words(post.created_at)+" ago", post_path(post) %>
        <% if post.likes.find_by(user_id: cookies.signed[:user_id]) %>
          | <%= link_to "Unvote", unlike_contribution_path(post), method: :delete %>
        <% end %>
        <% if cookies.signed[:user_id] == post.user.id %>
          | <%= link_to "Edit", edit_post_path(post) %> | <%= link_to "Delete", post, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %></td></tr>

      <% num+=1 %>
    <% end %>
    </tbody>
  </table>


  </tr></tbody></table></body></center></html>

app/views/posts/show.html.erb
<html lang="en"><center><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%  ">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%"  style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
              <a href="/posts/newest">new</a> | <a href="/posts/ask">ask</a> | <% if cookies.signed[:user_id] %><%= link_to 'threads', user_comments_user_path(cookies.signed[:user_id]) %><% else %><%= link_to 'threads', new_post_path %><% end %> | <a href="/posts/new">submit</a></span></td>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]= post_path(@post) %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %>
    </td>

  </tr></table></td></tr>

  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
    <tr>
      <td width="5px"><% if @post.likes.find_by(user_id: cookies.signed[:user_id]) %>
          <div class="hiddenarrow"></div>
        <% elsif @post.user_id == cookies.signed[:user_id] %>
          <div style="color:#ff6600">*</div>
        <% else %>
          <%= link_to like_contribution_path(@post), method: :put do %>
            <div class="votearrow" title="upvote"></div>
          <% end %>
        <% end %></td>
      <td><% if @post.url != "" %>
        <%= link_to @post.title, @post.url %>
      <% else %>
        <%= link_to @post.title, post_path(@post) %>
      <% end %></td>
    </tr>
    <tr><td style="position:relative;left:20px" class="subtext" colspan="3"><%= @post.points %> points by
      <% if @post.user_id == cookies.signed[:user_id] %>
        <%= link_to @post.user.name, edit_user_path(@post.user) %>
      <%else %>
        <%= link_to @post.user.name, user_path(@post.user) %>
      <% end %>
      <%= link_to time_ago_in_words(@post.created_at)+" ago", post_path(@post) %>
      <% if @post.likes.find_by(user_id: cookies.signed[:user_id]) %>
        | <%= link_to "Unvote", unlike_contribution_path(@post), method: :delete %>
      <% end %>
      <% if cookies.signed[:user_id] == @post.user.id %>
        | <%= link_to "Edit", edit_post_path(@post) %> | <%= link_to "Delete", @post, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
      <% end %>
      <tr>
      <td style="position:relative;left:20px" class="text" colspan="3"><%= simple_format(@post.text) %></td>
      </tr>



    </tbody></table>

    <%= form_for @comment, url: post_path(@post), html: {method: :post} do |form| %>
    <table style="background-color:#f6f6ef;width:85%">
    <tr>
      <td style="position:relative;left:20px" colspan="3"><%= form.text_area :text, cols:60, rows:6 %></td>
      <%= form.hidden_field :post_id, value: @post.id %>
    </tr>
    <tr>
      <td style="position:relative;left:20px" class="actions" colspan="3"> <%= form.submit 'add comment' %></td>
    </tr>
    </table>
  <% end %>

    <table style="background-color:#f6f6ef;width:85%">
  <% @post.comments.each do |comment| %>
        <tr>
        <td width="5px"><% if comment.likes.find_by(user_id: cookies.signed[:user_id]) %>
            <div class="hiddenarrow"></div>
          <% elsif comment.user_id == cookies.signed[:user_id] %>
            <div style="color:#ff6600">*</div>
          <% else %>
            <%= link_to like_contribution_path(comment), method: :put do %>
              <div class="votearrow" title="upvote"></div>
            <% end %>
          <% end %></td>
        <td class="subtext" colspan="3">
          <% if comment.user_id == cookies.signed[:user_id] %>
            <%= link_to comment.user.name, edit_user_path(comment.user) %>
          <%else %>
            <%= link_to comment.user.name, user_path(comment.user) %>
          <% end %>
          <%= link_to time_ago_in_words(comment.created_at)+" ago", interaction_path(comment) %>
          <% if comment.likes.find_by(user_id: cookies.signed[:user_id]) %>
            | <%= link_to "Unvote", unlike_contribution_path(comment), method: :delete %>
          <% end %>
        </td></tr>
          <tr>
            <td style="position:relative;left:20px;color:#000000" class="text" colspan="3"><%= simple_format(comment.text) %></td>
          </tr>
        <tr><td></td><td style="font-size:10px;text-decoration: underline"><%= link_to 'reply', interaction_path(comment) %></td></tr>
        <tr><td></td><td><% comment.replies.each do |reply|  %>
            <%= render 'reply', reply: reply %>
            <% end %>
        </td></tr>
  <% end %>
    </table>

          </tr></tbody>
</table></body></center></html>

app/views/posts/user_submissions.html.erb
<html lang="en"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="https://news.ycombinator.com/news.css?FMTtyazs2F7t6MWhtEEG">
  <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
  <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
  <title>Hacker News</title></head><center><body><table id="hnmain" border="0" cellpadding="0" cellspacing="0"  style="width:85%">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/"><img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/">Hacker News</a></b>
      <a href="/posts/newest">new</a> | <a href="/posts/ask">ask</a> | <% if cookies.signed[:user_id] %><%= link_to 'threads', user_comments_user_path(cookies.signed[:user_id]) %><% else %><%= link_to 'threads', new_post_path %><% end %> | <a href="/posts/new">submit</a> | <a style="color:#ffffff"><%= User.find(cookies.signed[:user_id]).name+"'s submissions" %></a></span></td>
    <td style="text-align:right;color:#000000">
      <% cookies.signed[:callback]='/' %>
      <% if cookies.signed[:user_id] %>
        <%= link_to User.find(cookies.signed[:user_id]).name, edit_user_path(User.find(cookies.signed[:user_id])), style: "color:#000000"  %> | <%= link_to 'logout', '/logout', style: "color:#000000" %>
      <% else %>
        <%= google_sign_in_button 'login', proceed_to: '/login', class: 'loginbutton' %>
      <%end %></td>
  </tr></table></td></tr>
  <tbody>
  <tr><table style="background-color:#f6f6ef;width:85%">
    <tbody>
    <% num=1 %>
    <% @posts.each do |post| %>
      <tr>
        <td width="10px"><%= num %>.</td>
        <td width="5px"><% if post.likes.find_by(user_id: cookies.signed[:user_id]) %>
            <div class="hiddenarrow"></div>
          <% elsif post.user_id == cookies.signed[:user_id] %>
            <div style="color:#ff6600">*</div>
          <% else %>
            <%= link_to like_post_path(post), method: :put do %>
              <div class="votearrow" title="upvote"></div>
            <% end %>
          <% end %></td>
        <td><%= link_to post.title, post_path(post) %></td>
      </tr>
      <tr><td style="position:relative;left:53px" class="subtext" colspan="3"><%= post.points %> points by <%= link_to post.user.name, user_path(post.user) %> <%= link_to time_ago_in_words(post.created_at)+" ago", post_path(post) %>
        <% if post.likes.find_by(user_id: cookies.signed[:user_id]) %>
          | <%= link_to "Unvote", unlike_post_path(post), method: :delete %>
        <% end %>
        <% if cookies.signed[:user_id] == post.user.id %>
          | <%= link_to "Edit", edit_post_path(post) %> | <%= link_to "Delete", post, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %>
        <% num+=1 %>
    <% end %>
    </tbody>
  </table>


  </tr></tbody></table></body></center></html>